"""initial schema

Revision ID: e4b073ae597e
Revises: 
Create Date: 2026-01-05 10:33:13.559081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b073ae597e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'profile',
        sa.Column('total_posts', sa.Integer(), nullable=False, server_default='0')
    )

    op.add_column(
        'profile',
        sa.Column('total_likes', sa.Integer(), nullable=False, server_default='0')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'total_likes')
    op.drop_column('profile', 'total_posts')
    # ### end Alembic commands ###
